/**
 * 标准 Obsidian 插件 esbuild 打包:main.ts(+ src/sync.mjs)→ main.js(CJS,供 Obsidian 加载)。
 *   node esbuild.config.mjs              开发(watch + sourcemap inline)
 *   node esbuild.config.mjs production   生产(无 watch、无 sourcemap、minify)
 *
 * obsidian / electron / Node 内置模块 external 掉(Obsidian 运行时提供)。
 */
import esbuild from "esbuild";
import process from "process";
import builtins from "builtin-modules";

const prod = process.argv[2] === "production";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD —— 墨爪 InkClaw Sync 插件。
源码见 main.ts / src/sync.mjs。
*/`;

const ctx = await esbuild.context({
  banner: { js: banner },
  entryPoints: ["main.ts"],
  bundle: true,
  external: [
    "obsidian",
    "electron",
    "@codemirror/autocomplete",
    "@codemirror/collab",
    "@codemirror/commands",
    "@codemirror/language",
    "@codemirror/lint",
    "@codemirror/search",
    "@codemirror/state",
    "@codemirror/view",
    "@lezer/common",
    "@lezer/highlight",
    "@lezer/lr",
    ...builtins,
  ],
  format: "cjs",
  target: "es2018",
  logLevel: "info",
  sourcemap: prod ? false : "inline",
  treeShaking: true,
  minify: prod,
  outfile: "main.js",
});

if (prod) {
  await ctx.rebuild();
  await ctx.dispose();
} else {
  await ctx.watch();
}
